version: 2

# ============================================================================
# BRONZE LAYER - RAW DATA SOURCES
# ============================================================================
# This file defines where your raw data lives in Snowflake.
# In dbt, you reference these using: {{ source('raw', 'table_name') }}
#
# The seed CSV files (in /seeds folder) are loaded here via `dbt seed`
# ============================================================================

sources:
  - name: raw
    description: Raw e-commerce data (Bronze Layer)
    schema: raw

    tables:
      # Customer master data
      - name: customers
        description: Customer information from the CRM system
        columns:
          - name: customer_id
            description: Unique customer identifier
            tests:
              - unique
              - not_null
          - name: email
            description: Customer email address
            tests:
              - unique
              - not_null
          - name: loyalty_points
            description: Customer loyalty rewards points balance

      # Order transactions
      - name: orders
        description: Order header data from e-commerce platform
        columns:
          - name: order_id
            description: Unique order identifier
            tests:
              - unique
              - not_null
          - name: customer_id
            description: Foreign key to customers
            tests:
              - not_null

      # Order line items
      - name: order_items
        description: Individual products within each order
        columns:
          - name: order_item_id
            description: Unique line item identifier
            tests:
              - unique
              - not_null

      # Product catalog
      - name: products
        description: Product catalog data
        columns:
          - name: product_id
            description: Unique product identifier
            tests:
              - unique
              - not_null

      # Product categories
      - name: categories
        description: Product category master data
        columns:
          - name: category_id
            description: Unique category identifier
            tests:
              - unique
              - not_null
          - name: category_name
            description: Display name of the category
            tests:
              - not_null
          - name: department
            description: Parent department grouping
          - name: created_at
            description: Timestamp when category was created

      # Marketing campaigns
      - name: marketing_campaigns
        description: Marketing campaign performance data
        columns:
          - name: campaign_id
            description: Unique campaign identifier
            tests:
              - unique
              - not_null

      # Customer reviews
      - name: reviews
        description: Customer product reviews and ratings
        columns:
          - name: review_id
            description: Unique review identifier
            tests:
              - unique
              - not_null
          - name: product_id
            description: Foreign key to products table
            tests:
              - not_null
          - name: customer_id
            description: Foreign key to customers table
            tests:
              - not_null
          - name: rating
            description: Product rating from 1 (poor) to 5 (excellent)
            tests:
              - not_null
          - name: review_title
            description: Short summary title of the review
          - name: review_text
            description: Full text content of the review
          - name: review_date
            description: Date when the review was submitted
